version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tax-chatbot-backend
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - MODEL_NAME=${MODEL_NAME:-gemini-2.5-flash}
      - TEMPERATURE=${TEMPERATURE:-0.7}
      - MAX_OUTPUT_TOKENS=${MAX_OUTPUT_TOKENS:-2048}
      - API_TITLE=${API_TITLE:-Tax Reform AI Chatbot}
      - API_VERSION=${API_VERSION:-1.0.0}
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api/v1/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - tax-chatbot-network

networks:
  tax-chatbot-network:
    driver: bridge
